/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mandelbrots;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.MemoryImageSource;
import java.util.Stack;

/**
 *
 * @author mbaltais3
 */
public class Mandelbrot extends javax.swing.JFrame {
    int augst, plat;
    double Ano,Alidz,Bno,Blidz, gradient;
    int pressedX1,pressedX2,pressedY1,pressedY2,pressedX3,pressedY3;
    boolean zimejums = false;
    Stack<Double> steks = new Stack<Double>(); 
    double Anoj, Alidzj, Bnoj, Blidzj;
    
    public void zimesana(double Ano, double Alidz, double Bno, double Blidz){
    
    augst = Panel.getHeight();
    plat = Panel.getWidth();
    
    
    double cReal, aVecais, cImag, bVecais, a, b, aJaunais, bJaunais, zMod;

    double db = (Blidz - Bno)/augst;
    double da = (Alidz - Ano)/plat;
    int pixels[] = new int[plat*augst];
    
    
    Image image;
   
    Graphics g=Panel.getGraphics();
    
    int m = 10;
    int j=0;
    for(int y =0; y < augst; y++){
        b = Bno + y*db;
        for (int x = 0; x < plat; x++){
            a = Ano + x*da;
            
            cReal = a;
            aVecais = a;
            cImag = b;
            bVecais = b;
            
            int i = 0;
            
            do{
            aJaunais =  (aVecais*aVecais)-(bVecais*bVecais)+cReal;  
            bJaunais = 2*aVecais*bVecais + cImag;
            zMod = (aJaunais*aJaunais) + (bJaunais*bJaunais);
            aVecais = aJaunais;
            bVecais = bJaunais;
            i = i+1;
            } while (i < 100 && zMod <= m);
            
                gradient = i + 1.0 - Math.log(Math.log(Math.abs(zMod)))/Math.log(2.0);
               gradient = gradient/100;
            
            if (i >= 100){
                  pixels[j] = (255<<24)|(0<<16)|(255<<8) | 0;
                } else {
                
               pixels[j] = Color.HSBtoRGB((float) (0.95f +2 * gradient),0.60f,1.0f);
//              pixels[j] = (255<<24)|(256<<16)|(0<<8)|0; 
              
            }
            j++;
            
            }
            
        }
        image = createImage(new MemoryImageSource(plat,augst,pixels,0,plat));
        g.drawImage(image,0,0,null);
    }
    
        public void zoom(){
        steks.push(Ano);
        steks.push(Bno);
        steks.push(Alidz);
        steks.push(Blidz);
 
        Anoj = Ano + (pressedX1*((Alidz-Ano)/plat));
        Alidzj = Ano + (pressedX2*((Alidz-Ano)/plat));
        Bnoj = Blidz - (pressedY2*((Blidz-Bno)/augst));
        Blidzj = Blidz - (pressedY1*((Blidz-Bno)/augst));
        
        Ano = Anoj;
        Bno = Anoj;
        Alidz = Alidzj;
        Blidz = Blidzj;
        
        zimesana(Ano,Bno,Alidz,Blidz);
//        
//        System.out.println("X1: "+pressedX1+ " X2: "+pressedX2);
//        System.out.println("Y1: "+pressedY1+ " Y2: "+pressedY2);
//        System.out.println("ano: "+aNo + " alidz: " + aLidz + " bno: "+bNoj + " blidz: "+bLidzj + " ");
    }
    
    
    
    public Mandelbrot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Ano_text = new javax.swing.JTextField();
        Bno_text = new javax.swing.JTextField();
        Blidz_text = new javax.swing.JTextField();
        Alidz_text = new javax.swing.JTextField();
        poga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jLabel1.setText("A");

        jLabel2.setText("B");

        jLabel3.setText("No");

        jLabel4.setText("Līdz");

        Ano_text.setText("-2");
        Ano_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ano_textActionPerformed(evt);
            }
        });

        Bno_text.setText("-2");
        Bno_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bno_textActionPerformed(evt);
            }
        });

        Blidz_text.setText("2");
        Blidz_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Blidz_textActionPerformed(evt);
            }
        });

        Alidz_text.setText("2");
        Alidz_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alidz_textActionPerformed(evt);
            }
        });

        poga.setText("Izveido!");
        poga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pogaMouseClicked(evt);
            }
        });
        poga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pogaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)
                        .addGap(334, 334, 334))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Alidz_text, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(27, 27, 27)
                                        .addComponent(Ano_text, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Bno_text, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Blidz_text, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(poga, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Ano_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bno_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Blidz_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alidz_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ano_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ano_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ano_textActionPerformed

    private void Bno_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bno_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bno_textActionPerformed

    private void Blidz_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Blidz_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Blidz_textActionPerformed

    private void Alidz_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alidz_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Alidz_textActionPerformed

    private void pogaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pogaMouseClicked
    Ano = Double.parseDouble(Ano_text.getText());
    Bno = Double.parseDouble(Bno_text.getText());
    Alidz = Double.parseDouble(Alidz_text.getText());
    Blidz = Double.parseDouble(Blidz_text.getText());
    zimesana(Ano,Alidz,Bno,Blidz);
    zimejums = true;
    }//GEN-LAST:event_pogaMouseClicked

    private void pogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pogaActionPerformed

    }//GEN-LAST:event_pogaActionPerformed

    private void PanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMousePressed
        pressedX1 = 0;
        pressedX2 = 0;
        pressedY1= 0;
        pressedY2= 0;
        pressedX1 = evt.getX();
        pressedY1 = evt.getY();
    }//GEN-LAST:event_PanelMousePressed

    private void PanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMouseReleased
         pressedX2 = evt.getX();
        pressedY2 = pressedY1 + pressedX2 - pressedX1;
            if (zimejums == true) {
                zoom(); 
    }//GEN-LAST:event_PanelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mandelbrot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mandelbrot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mandelbrot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mandelbrot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mandelbrot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alidz_text;
    private javax.swing.JTextField Ano_text;
    private javax.swing.JTextField Blidz_text;
    private javax.swing.JTextField Bno_text;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton poga;
    // End of variables declaration//GEN-END:variables
}
